// Generated by scripts/generate-guidance.mjs from skills/context-management/CORE.md and TOOL-CONTRACTS.md.
// Do not edit directly.

export const ACM_CORE_MARKER = "<!-- PI-CONTEXT:ACM-CORE:v1 -->";

export const ACM_CORE = "## 会话上下文管理\n\n会话变长时，你可以把已经消化完的过程折叠掉，让对话保持精简，把注意力留给接下来的工作。折叠不是删除——原文留在历史树里，需要时随时能取回。\n\n你有三个工具：\n\n- **acm_checkpoint** — 给当前状态起个名字存档。随时可用，不改变当前对话。想做有风险的操作、或准备折叠一大段历史之前，先存个档方便回来。\n- **acm_timeline** — 查看会话树：当前对话主线、所有存档点、或搜索历史。不清楚对话结构或要找某个存档点时用。\n- **acm_travel** — 把一段已经得出结论、不再需要回头细看的过程，折叠成一份简短交接说明。对话变短，原文留在树里，一次 travel 就能取回。\n\n### 什么时候该折叠\n\n当你能清楚复述一段过程得出了什么结论、还留着什么未解决的问题、下一步要做什么——而且不再需要回头看这段过程里的细节时，就可以折叠它了。如果还说不清楚，就先别折，继续工作直到心里有数。\n\n折叠时写一份交接说明（handoff），让一个完全不知道前情的新对话也能接着干：目标是什么、现在进展到哪、已知什么、还没解决什么、下一步具体做什么。写不出这样的说明，说明这段过程还没消化完，还不到折叠的时候。\n\n折叠前先存档当前状态，万一要恢复就能回去。\n\n### 折叠之后\n\n折叠完成后，交接说明就是你的当前状态——直接按它说的下一步继续。不要回头重读刚折叠的内容\"确认一下\"，那样折叠就没意义了。只有交接说明里明确标记的未决问题，或之后有新的外部变化改了事实，才需要去验证。\n\n折叠只改变对话内容，不回滚文件、命令或任何外部改动。\n\n### context 占用提示\n\n普通工具结果末尾会带一行 `[ctx N%]`，表示当前对话占用了多少 context。数字变大说明对话在变长。这只是给你参考的——什么时候折叠由你判断，不是看数字到了某个值就折。";

export const TOOL_DESCRIPTIONS = {
  "checkpoint": "给当前会话状态起个名字存档，以后能用这个名字回到这个状态。不改变当前对话。省略 target 时自动存到调用前最近的有效位置；传 target 可以存指定的历史节点。",
  "timeline": "查看会话树。view 选 active(默认，看当前对话主线)、checkpoints(看所有存档点)、search(搜历史内容)、tree(看整棵树结构)。",
  "travel": "把一段已完成的过程折叠成一份简短交接说明。对话变短，原文留在历史树里随时能取回。target 是折叠到哪个存档点或节点(那段过程开始之前的位置)，handoff 是写给折叠后的自己的交接说明。必须单独调用，不能和其他工具混在一个 batch。"
} as const;

export const PROMPT_SNIPPETS = {
  "checkpoint": "存档当前状态",
  "timeline": "查看会话树和存档点",
  "travel": "折叠一段已完成的过程"
} as const;

export const PROMPT_GUIDELINES = {
  "checkpoint": "acm_checkpoint 随时可用，不改变当前对话，想存就存。",
  "timeline": "acm_timeline 的 view 按需要选:active 看主线，checkpoints 看存档点，search 搜内容，tree 看结构。",
  "travel": "acm_travel 折叠后直接按 handoff 的 next 继续，不要重读刚折叠的内容;折叠不回滚文件或命令。"
} as const;

export const GUIDANCE_CUES = {
  "checkpoint": "已存档。当前对话不变。需要时用这个名字回到这个状态。",
  "travel": "已折叠。handoff 是现在的状态，按它的 next 继续。不要重读刚折叠的内容。",
  "rebaseCheck": "当前对话已有一层交接说明，再折叠会再加一层。可以考虑把已有的几层合并成一份更早的，但不强制。",
  "advancedTargetPointer": "如果 target 还是选不准，先把这段过程得出了什么结论、下一步做什么想清楚，再选它开始之前的存档点。",
  "advancedExceptionalPointer": "出错了先别急着重试。看清楚报错，确认折叠到底有没有生效，再决定怎么办。",
  "timelineActive": "active 是当前对话主线。看看有没有已经不需要的过程可以折叠。",
  "timelineCheckpoints": "checkpoints 列出所有存档点。折叠时选这段过程开始之前的那个存档点。",
  "timelineSearch": "search 搜整棵历史树。缩小范围，找到要折叠的那段开始之前的节点。",
  "timelineTree": "tree 看树结构。别选要折叠的那段里面的节点，也别选另一条分支上的。"
} as const;

export const TREE_SUMMARY_INSTRUCTIONS = "把这条要放弃的对话分支总结成一份交接说明，让以后回来的人能接着干。\n\n就写这七行，每行一个，按顺序，不要加别的标题:\n\nGoal: 这条分支想干什么。\nState: 这里得出了什么结论、有什么证据、还有什么没搞清楚的。写清楚还在用的文件、符号、数值。\nEvidence: 能直接验证的线索——文件路径、命令、ID。没有就写 none。\nExternal: 对话之外留下的改动——改了哪些文件、跑了什么命令。没有就写 none。\nExclusions: 这里试过但行不通的方向，免得重来。没有就写 none。\nRecover: 最有用的存档点或节点 ID，方便回来。没有就写 none。\nNEXT: 如果接着干，下一步具体做什么。\n\n保留准确的文件路径、函数名、错误信息和数字，这些比描述重要。整体简短。";

export const RECOVERY_GUIDANCE = {
  "nameCollision": "这个名字已经被别的存档点用了。换个名字——保留原意，加个序号、范围或日期。别覆盖原来的。",
  "hostCapability": "Pi 的 SessionManager 不支持这个操作。停下，报告这个错误，确认 Pi 版本支持后再试。",
  "rollbackFailed": "备份存档点没删掉。记下它的名字和节点 ID 作为恢复线索，再重试。",
  "branchRolledBack": "折叠没成功，备份存档点已经回滚。修好报的错再重试。",
  "rollbackSkipped": "因为折叠可能已经生效，备份存档点没自动删。保留这个备份指针，先看看当前节点再重试。",
  "refreshPending": "折叠生效了，但重建对话内容还没完成。用报的 summary 节点作为备用，下次重建还不行就看 context sync 状态。",
  "restoredHistory": "这次 travel 恢复了之前的历史(context 变大了)。如果是有意的取回，拿走需要的细节就继续;如果是误操作，travel 回之前的存档点。",
  "refreshExhausted": "重建对话重试次数用完了。重新加载会话，确认当前分支对了再继续。"
} as const;
